---
- name: Ensures phpmyadmin dir exists
  file:
    path: "{{ pma_dir }}"
    state: directory

- name: Creating phpmyadmin pma.yml file
  template:
    src: pma.yml.j2
    dest: "{{ pma_dir }}/pma.yml"

- name: Deploy pma
  docker_stack:
    state: present
    name: "pma"
    compose:
      - "{{ pma_dir }}/pma.yml"
  register: phpmyadmin_output

- name: Print create and start phpmyadmin
  debug:
    var: phpmyadmin_output
