---
- name: Ensures phpmyadmin dir exists
  file:
    path: "{{ pma_dir }}"
    state: directory

- name: Creating phpmyadmin docker-compose.yml file
  template:
    src: docker-compose.yml.j2
    dest: "{{ pma_dir }}/docker-compose.yml"

- name: Tear down existing services
  docker_compose:
    project_src: "{{ pma_dir }}"
    state: absent

- name: Create and start phpmyadmin
  docker_compose:
    project_src: "{{ pma_dir }}"
  # register: phpmyadmin_output

# - name: Print create and start phpmyadmin
#   debug:
#     var: phpmyadmin_output
