version: "3"
services:
  ansible:
    image: kabaconde/ansible-docker:provision
    working_dir: /ansible
    volumes:
      - ./playbooks:/ansible
      - ~/.ssh:/tmp/.ssh:ro
    command: tail -f /dev/null && /bin/mount-ssh.sh
    environment:
      ANSIBLE_STDOUT_CALLBACK: debug
