ansible_python_interpreter: /usr/bin/python3

# Values of raw_vars will be wrapped in `{% raw %}` to avoid templating problems if values include `{%` and `{{`.
# Will recurse dicts/lists. `*` is wildcard for one or more dict keys, list indices, or strings.
raw_vars:
  - vault_users.*.password
  - vault_users.*.salt

app_domain: domain.com
project_name: project_name
server_base_path: /var/www

www_root: /var/www/sites

#-------------------------------------------------------------------------------
# Network Settings
#-------------------------------------------------------------------------------

# Additional open ports (besides 22, 80 & 443)
open_ports: []
