---
- name: Ensures netdata dir exists
  file:
    path: "{{ netdata_dir }}"
    state: directory

- name: Creating netdata docker-compose.yml file
  template:
    src: docker-compose.yml.j2
    dest: "{{ netdata_dir }}/docker-compose.yml"

- name: Tear down existing services
  docker_compose:
    project_src: "{{ netdata_dir }}"
    state: absent

- name: Create and start netdata
  docker_compose:
    project_src: "{{ netdata_dir }}"
  # register: netdata_output

# - name: Print create and start netdata
#   debug:
#     var: netdata_output
