---
- import_playbook: variable-check.yml
  vars:
    playbook: rollback.yml

- name: Test Connection
  hosts: "{{ env }}"
  gather_facts: false
  vars:
    dynamic_user: false
  roles:
    - { role: connection, tags: [connection, always] }

- name: Rollback a Deploy
  hosts: "{{ env }}"
  remote_user: "{{ web_user }}"
  roles:
    - rollback
